on:
  pull_request:
    branches:
      - master
  push: 
    tags:
      - 'v*'
    branches:
      - master
env:
  REGISTRY: docker.io
  IMAGE_NAME: pawcho-weather-app
jobs:
  build:
    env:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKER_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}

    name: Build, test and push docker image for weather-app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Docker metadata definitions
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          flavor: latest=true
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          load: true
          tags: local-${{ env.IMAGE_NAME }}:test
          cache-from: |
            type=registry,ref=${{ env.DOCKER_IMAGE }}:cache
          cache-to: |
            type=registry,ref=${{ env.DOCKER_IMAGE }}:cache,mode=max
          ssh: default

      - name: Scan image for CVE's
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: local-${{ env.IMAGE_NAME }}:test
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      - name: Push image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: | 
            ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ steps.metadata.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}:latest
          cache-from: |
            type=registry,ref=${{ env.DOCKER_IMAGE }}:cache
          cache-to: |
            type=registry,ref=${{ env.DOCKER_IMAGE }}:cache,mode=max
          ssh: default